version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/acshb-react-project-template-volume"
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - "${PORT}:80"
    networks:
      - acshb-react-project-template-network
volumes:
  app_data:
networks:
  acshb-react-project-template-network:
    driver: bridge
